### Environment constants

ARCH ?=
CROSS_COMPILE ?=
export

### general build targets

all:
	$(MAKE) all -e -C libloragw


pre_install:
	$(MAKE) pre_install -e -C libloragw 


clean:
	$(MAKE)	clean -e -C libloragw


### EOF
